### ISSUE TITLE
NBT Editor do not work!!

### ISSUE THREAD

**Issue by ErythroCraft** [misode/vscode-nbt#1]
Hello

The editor is not working to edit nbt data.

It is successful installed, but not working to edit. 

Why?

**Comment by misode** [comment]
It's mostly a WIP extension and currently only supports viewing. Maybe I should rename the extension for the time being.

**Comment by ErythroCraft** [comment]
Maybe you want work with a fork of https://github.com/jaquadro/NBTExplorer .

I ask the outhor jaquadro.

**Comment by misode** [comment]
I already know about NBTExplorer, NBTStudio, but this is a VSCode extension. I can't just copy another piece of software.

**Comment by ErythroCraft** [comment]
OK
