### ISSUE TITLE
Unable to expand Region Chunks

### ISSUE THREAD

**Issue by spoorn** [misode/vscode-nbt#11]
I can't expand Chunk data in the region `.mca` files

**Comment by misode** [comment]
@spoorn Could you upload the region file that is causing this issue?

**Comment by spoorn** [comment]
I can't expand the + Chunk data in any region file

**Comment by spoorn** [comment]
Here's an example, I had to append a .txt extension to upload the file to github, but you can remove the extension and try to open in vs code

[r.0.3.mca.txt](https://github.com/misode/vscode-nbt/files/6759446/r.0.3.mca.txt)

**Comment by misode** [comment]
A fix for this is released as v0.5.5 🚀 Thanks a lot for reporting this issue!
