### ISSUE TITLE
Publishing on Open VSX

### ISSUE THREAD

**Issue by ashhhleyyy** [misode/vscode-nbt#19]
Publishing on the [Open VSX registry](https://open-vsx.org) as well as the VSCode marketplace would allow people to use the extension with other vscode-based editors such as VSCodium or Gitpod

**Comment by misode** [comment]
Published, and in the process of getting ownership to the namespace https://open-vsx.org/extension/misodee/vscode-nbt

**Comment by Legendary-Creeper** [comment]
Hey @misode, the extension of yours provided on Open VSX hasn't received any updates since v0.6.7; more specifically, it has been out of date for approximately four years. I wanted to ask why this is the case and kindly request that you push updates to Open VSX again. :)
