### ISSUE TITLE
Feature request: Search in NBT

### ISSUE THREAD

**Issue by magicus** [misode/vscode-nbt#2]
Great plugin! I just discovered it when NBTExplorer stopped working when I upgraded MacOS. The major missing functionality is of course editing/saving, but judging from the commit history I suspect this is coming back when it is stable. (Let me know if you want some help with it!)

I do miss the ubiquitous search box in the NBT viewer. Perhaps it's more difficult to get search functionality for a web ui component, so it's maybe not a simple request. Would you accept a PR, if I tried to implement it?

**Comment by misode** [comment]
Search would have to be done from scratch, but it would be a very nice feature to have. 

PR's are appreciated yes, I don't thing there are any major technical hurdles to overcome for this feature, but it's going to be a bit of work to have it match the native vscode search experience.

**Comment by misode** [comment]
I started development of this in the `dev` branch

**Comment by misode** [comment]
Search is now fully implemented.
