### ISSUE TITLE
Feature Request: Open .dat_old, .dat_new etc.

### ISSUE THREAD

**Issue by Dahesor** [misode/vscode-nbt#20]
Some .dat files, like ```<player>.dat```, always has a backup named ```<player>.dat_old```.
But the extension can only open .dat files, so if I want to open .dat_old I'll have to rename it.

I believe it will makes this extension better by adding .dat_old or things like that into the Filename Pattern.

**Comment by misode** [comment]
dat_old seems like a good idea. Does dat_new also exist? I've never heard about that one.

**Comment by JochCool** [comment]
`level.dat_old` is just a backup of `level.dat`, there is no `level.dat_new`.
