### ISSUE TITLE
Add textures manually

### ISSUE THREAD

**Issue by Lianecx** [misode/vscode-nbt#22]
Being able to add textures for specific block ids would be a very handy feature. I'm currently trying to open a 1.19 nbt file in the 3d viewer, but some of the new block textures are missing (sculk, reinforced deepslate, etc) and i have no idea how to add resources for them

**Comment by Lianecx** [comment]
Update: I actually managed to add an existing mc texture for the reinforced deepslate by editing `res/generated/assets.js`  and `res/generated/blocks.js` . Then i added a texture for the reinforced_deepslate in `res/generated/atlas.png`. 
Very complicated process though, a feature would make this much easier.

**Comment by misode** [comment]
I'm currently in the process of using [mcmeta](https://github.com/misode/mcmeta/tree/atlas/all) to dynamically load the textures based on the version of the structure, that should be sufficient for most people.

**Comment by Lianecx** [comment]
Well the 1.19 snapshot is an experimental snapshot which means You cant directly download the jar because its a special link. And what about modded structures?

**Comment by Lianecx** [comment]
Hmm okay
