### ISSUE TITLE
blocks behind slabs not rendering

### ISSUE THREAD

**Issue by ddrs15** [misode/vscode-nbt#23]
have found a problem with a structure with deepslate slabs, where the blocks behind the slabs arent rendered on the side the slab touches, creating holes in the render. see example screenshot
![Screenshot_3556](https://user-images.githubusercontent.com/47245725/157218481-161432f0-bd84-4469-9ff6-87f9de74b020.png)
have only seen it happen with these deepslate slabs

**Comment by misode** [comment]
Thanks for reporting this issue! A fix was just published as v0.6.8
