### ISSUE TITLE
version 0.7.2 render issue

### ISSUE THREAD

**Issue by fnaith** [misode/vscode-nbt#27]
version 0.7.2 cannot display some blocks
![0_7_2](https://user-images.githubusercontent.com/11421034/167288744-6a694c12-282d-4b95-8cbb-9f1f25fdd5bc.PNG)

but this nbt file was fine when I use version 0.6.8
![0_6_8](https://user-images.githubusercontent.com/11421034/167288764-0f42fd8b-9b40-4980-9cea-e071501a53ef.PNG)

nbt as following
[demo.zip](https://github.com/misode/vscode-nbt/files/8646657/demo.zip)

**Comment by misode** [comment]
@fnaith Your `demo.nbt` file has blocks with weird blockstate properties. Some properties are missing (for example grass blocks is missing `snowy=false`), and repeaters are missing `locked` and `powered`, and they have an extra property `construct_beat`.

I'm puzzled how the previous version managed to show these, and I guess this means it should be more lax. But where did this NBT file come from?

**Comment by fnaith** [comment]
@misode I composed this demo.nbt by my program, which don't apply default property for blocks.
Also, somehow minecraft 1.18.x can load it.

**Comment by misode** [comment]
Turned out I made a mistake loading the default block states when refactoring. A fix is going out as v0.7.3, thanks for reporting this!

**Comment by fnaith** [comment]
Thanks you~~. BTW, I use this tool everyday. Very useful to check structure.
https://www.youtube.com/channel/UCOxUb12S7z-dv4T4M6fK8Wg/videos
