### ISSUE TITLE
NBT Data Type Hotkey Additions

### ISSUE THREAD

**Issue by catter1** [misode/vscode-nbt#36]
You can add a new tag via a button (blue arrow in image). When you do so, it creates the tag below (red arrow in image). Now, currently, before you type anything, you can pre-select the data type by hot keys. For example, push `i` and it swaps to `int`, or push `l` and it swaps to `long`. Then you can immediately start typing without having to click on the text box.

There are a couple data types that don't have this capability - mainly `list` and `string`, probably because `l` and `s` already map to `long` and `short`, respectively. My suggestion: add some hotkeys for those data types. I use those two a lot, and just the added convenience is helpful. Maybe `g` for `string`, and `t` for `list`.

No idea if there are others missing. Thanks!

![image](https://user-images.githubusercontent.com/63272345/197774793-2fb6291d-01f5-4120-b394-3aaf2af16792.png)

**Comment by misode** [comment]
I think you can type `li` and `st` for those. This is the built-in behavior of dropdowns so I'm not sure how easy it will be to customize this.

**Comment by catter1** [comment]
At least on my client, `li` and `st` do not work


https://user-images.githubusercontent.com/63272345/197809755-c314b796-a643-41b3-be5e-8b29542d0cbf.mp4

**Comment by misode** [comment]
I made `S` and `L` default to string and list respectively because I figured those are used more often. This is the full list:
![image](https://user-images.githubusercontent.com/17352009/210899335-ae6c44df-d2c2-4caa-bffe-2e72b94b07a2.png)

**Comment by catter1** [comment]
Looks excellent! Thank you!
