### ISSUE TITLE
NBT file is modified despite no visible changes

### ISSUE THREAD

**Issue by haykam821** [misode/vscode-nbt#4]
When viewing an NBT file and switching to another editor, the NBT file becomes modified, as indicated by the output of `git status`.

## Versions

* NBT Editor - v0.0.4
* Visual Studio Code - 1.53.2 (microsoft/vscode@622cb03f7e070a9670c94bae1a45d78d7181fbd4)
* Electron - 11.2.1
* Chrome - 87.0.4280.141
* Node.js - 12.18.3
* V8 - 8.7.220.31-electron.0
* OS - Darwin x64 20.2.0

**Comment by misode** [comment]
Hi, you're using `NBT Editor v0.0.4`, while the latest version of this repo is `NBT Viewer v0.3.2`. You need to uninstall the old extension. The reason for the switch is that I lost access to the original publisher account.

**Comment by haykam821** [comment]
This still occurs on NBT Viewer v0.3.2.

**Comment by misode** [comment]
Just to make sure, this happens when you make no edits in the visual editor and then you press `Ctrl+S`?

**Comment by haykam821** [comment]
Yes, it occurs when saving manually as well. The `files.autoSave` setting indicates that saving should only occur when an editor is dirty, but no such indicator like the one below is present:

![Dirty editor tab](https://user-images.githubusercontent.com/24855774/108609445-eb50d380-739b-11eb-9d05-99c9a1044c49.png)

The dirty editor indicator appears when changes are made through the visual editor, but despite not being present, the file itself is modified anyways.

**Comment by misode** [comment]
@haykam821 Do you have exact reproduction steps? I am not able to reproduce by simply opening, saving, closing files.

**Comment by haykam821** [comment]
I can reproduce this just by opening the file and running the 'File: Save' command.

**Comment by misode** [comment]
I released a potential fix with version `0.5.1`. @haykam821 Could you try if this fixes the problem for you?

**Comment by haykam821** [comment]
This issue is fixed in version 0.5.1.
