### ISSUE TITLE
Failed to apply edit: Expected chunk edit, but got 'remove'

### ISSUE THREAD

**Issue by carbsna** [misode/vscode-nbt#46]
(or another similar error message "Failed to apply edit: Expected chunk edit, but got 'set' ")

Having trouble to edit my mca file.
I have no clue about he meaning of this message, whether it means this editor don't support such editing, or i'm doing anything wrong.
This error message showing up when i'm in default view mode, trying to use the Remove/Add Tag/Rename button, or when i try to set the value.
I also tried go into SNBT view mode, delete the stuff right away, but it seems unable to save any changes i made.

Whatever it gives, i think it would be nice to put the meaning of this error message into README

**Comment by VirxEC** [comment]
I'm getting this same error, but editing the SNBT does work for me.
