### ISSUE TITLE
The contents of the .dat file are not displayed.

### ISSUE THREAD

**Issue by kaito02020424** [misode/vscode-nbt#52]
I would like to enable experimental features, change the world name, etc. in BDS, but when I open level.dat, nothing is displayed.
![image](https://github.com/misode/vscode-nbt/assets/104062884/550ad11e-3cb7-4993-8570-59c494d9ff95)
![image](https://github.com/misode/vscode-nbt/assets/104062884/cf919250-63ce-48bb-863f-e92b03fafff8)

**Comment by misode** [comment]
Could you attach the dat file that you're trying to open?

**Comment by kaito02020424** [comment]
I will attach it as soon as I get home.

**Comment by kaito02020424** [comment]
level.dat:
https://cdn.discordapp.com/attachments/1051130245014634586/1162146841060724766/level.dat


NBT-Viewer Version : 0.8.1

**Comment by misode** [comment]
You `level.dat` file is corrupted. Opening the file with other NBT tools gives the same result. When I check the binary representation of the file, the 4th byte means the root component ends immediately.
![image](https://github.com/misode/vscode-nbt/assets/17352009/f902bc15-e5d9-43b5-af05-373521a9ed3e)

Usually when this happens, you can use the `level.dat_old` file as a replacement.

**Comment by misode** [comment]
Thanks a lot for your report! version `0.8.2` has been released on the VSCode Marketplace!

**Comment by kaito02020424** [comment]
thx!
