### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Tonmyn** [misode/vscode-nbt#67]
![image](https://github.com/misode/vscode-nbt/assets/18096197/58d1013d-f264-47c9-a571-d7033476888a)
![image](https://github.com/misode/vscode-nbt/assets/18096197/9cc184b3-2a66-4d0c-a40a-bb4626c22ca3)

![2](https://github.com/misode/vscode-nbt/assets/18096197/6123272b-24c0-464d-9c96-eb7aee0303c6)
It will always be in a loading state

**Comment by JuceInUse** [comment]
Why are you trying to view a .dat file in a .nbt file viewer

**Comment by misode** [comment]
Could you open the output panel and show whether there are any errors? Ctrl+Shift+U, then select NBT Viewer

**Comment by Tonmyn** [comment]
![image](https://github.com/misode/vscode-nbt/assets/18096197/35cd2440-3575-4e4b-9edf-8519f8b160a3)
no any errors

**Comment by misode** [comment]
That is not the output panel, this is:
![image](https://github.com/misode/vscode-nbt/assets/17352009/ef690e80-d650-4278-8c99-b3ef136c06f4)

**Comment by misode** [comment]
It needs to download the resources (textures, models, etc) to render the blocks yeah. And it looks like that's the step it's getting stuck at. Is `raw.githubusercontent.com` blocked in your country?

**Comment by Tonmyn** [comment]
yes,it is blocked in my country.

**Comment by SYREB** [comment]
![image](https://github.com/user-attachments/assets/30c0d420-07c2-4035-bc71-c707de155a93)
![image](https://github.com/user-attachments/assets/7a8031ec-ecb8-41bf-8889-d57103ef5620)
![image](https://github.com/user-attachments/assets/f01913ba-f23d-4be9-8f26-edd1243e9d26)
Why is "NBT Viewer" not an option in my selections?

**Comment by misode** [comment]
> Why is "NBT Viewer" not an option in my selections?

The extension only activates when you open an `.nbt` (or similar) file

**Comment by SYREB** [comment]
> The extension only activates when you open an (or similar) file`.nbt`

The problem has been resolved, thank you for your patience!
